-- MySQL Script generated by MySQL Workbench
-- Fri Jun  1 19:54:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FerreteriaAdmin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FerreteriaAdmin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FerreteriaAdmin` DEFAULT CHARACTER SET utf8 ;
USE `FerreteriaAdmin` ;

-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Rol` (
  `idRol` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`UsuarioAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`UsuarioAdmin` (
  `idUsuarioAdmin` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `CodigoEmpresa` VARCHAR(45) NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuarioAdmin`, `Rol_idRol`),
  INDEX `fk_UsuarioAdmin_Rol_idx` (`Rol_idRol` ASC),
  CONSTRAINT `fk_UsuarioAdmin_Rol`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `FerreteriaAdmin`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Pedidos` (
  `idPedidos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaPedido` DATE NULL,
  `Estados_IdEstados` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, `Estados_IdEstados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Estados` (
  `IdEstados` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Pedidos_Estados_IdEstados` INT NOT NULL,
  PRIMARY KEY (`IdEstados`, `Pedidos_idPedidos`, `Pedidos_Estados_IdEstados`),
  INDEX `fk_Estados_Pedidos1_idx` (`Pedidos_idPedidos` ASC, `Pedidos_Estados_IdEstados` ASC),
  CONSTRAINT `fk_Estados_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos` , `Pedidos_Estados_IdEstados`)
    REFERENCES `FerreteriaAdmin`.`Pedidos` (`idPedidos` , `Estados_IdEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Catalogo` (
  `idCatalogo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCatalogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Catalogo_idCatalogo` INT NOT NULL,
  `UsuarioAdmin_idUsuarioAdmin` INT NOT NULL,
  `UsuarioAdmin_Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `Catalogo_idCatalogo`, `UsuarioAdmin_idUsuarioAdmin`, `UsuarioAdmin_Rol_idRol`),
  INDEX `fk_Categoria_Catalogo1_idx` (`Catalogo_idCatalogo` ASC),
  INDEX `fk_Categoria_UsuarioAdmin1_idx` (`UsuarioAdmin_idUsuarioAdmin` ASC, `UsuarioAdmin_Rol_idRol` ASC),
  CONSTRAINT `fk_Categoria_Catalogo1`
    FOREIGN KEY (`Catalogo_idCatalogo`)
    REFERENCES `FerreteriaAdmin`.`Catalogo` (`idCatalogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_UsuarioAdmin1`
    FOREIGN KEY (`UsuarioAdmin_idUsuarioAdmin` , `UsuarioAdmin_Rol_idRol`)
    REFERENCES `FerreteriaAdmin`.`UsuarioAdmin` (`idUsuarioAdmin` , `Rol_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Articulo` (
  `idArticulo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Pedidos_Estados_IdEstados` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Categoria_Catalogo_idCatalogo` INT NOT NULL,
  `UsuarioAdmin_idUsuarioAdmin` INT NOT NULL,
  `UsuarioAdmin_Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idArticulo`, `Pedidos_idPedidos`, `Pedidos_Estados_IdEstados`, `Categoria_idCategoria`, `Categoria_Catalogo_idCatalogo`, `UsuarioAdmin_idUsuarioAdmin`, `UsuarioAdmin_Rol_idRol`),
  INDEX `fk_Articulo_Pedidos1_idx` (`Pedidos_idPedidos` ASC, `Pedidos_Estados_IdEstados` ASC),
  INDEX `fk_Articulo_Categoria1_idx` (`Categoria_idCategoria` ASC, `Categoria_Catalogo_idCatalogo` ASC),
  INDEX `fk_Articulo_UsuarioAdmin1_idx` (`UsuarioAdmin_idUsuarioAdmin` ASC, `UsuarioAdmin_Rol_idRol` ASC),
  CONSTRAINT `fk_Articulo_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos` , `Pedidos_Estados_IdEstados`)
    REFERENCES `FerreteriaAdmin`.`Pedidos` (`idPedidos` , `Estados_IdEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria` , `Categoria_Catalogo_idCatalogo`)
    REFERENCES `FerreteriaAdmin`.`Categoria` (`idCategoria` , `Catalogo_idCatalogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_UsuarioAdmin1`
    FOREIGN KEY (`UsuarioAdmin_idUsuarioAdmin` , `UsuarioAdmin_Rol_idRol`)
    REFERENCES `FerreteriaAdmin`.`UsuarioAdmin` (`idUsuarioAdmin` , `Rol_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Atributos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Atributos` (
  `idAtributos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  `FechaPedido` VARCHAR(45) NULL,
  `Articulo_idArticulo` INT NOT NULL,
  `Articulo_Pedidos_idPedidos` INT NOT NULL,
  `Articulo_Pedidos_Estados_IdEstados` INT NOT NULL,
  PRIMARY KEY (`idAtributos`, `Articulo_idArticulo`, `Articulo_Pedidos_idPedidos`, `Articulo_Pedidos_Estados_IdEstados`),
  INDEX `fk_Atributos_Articulo1_idx` (`Articulo_idArticulo` ASC, `Articulo_Pedidos_idPedidos` ASC, `Articulo_Pedidos_Estados_IdEstados` ASC),
  CONSTRAINT `fk_Atributos_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo` , `Articulo_Pedidos_idPedidos` , `Articulo_Pedidos_Estados_IdEstados`)
    REFERENCES `FerreteriaAdmin`.`Articulo` (`idArticulo` , `Pedidos_idPedidos` , `Pedidos_Estados_IdEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaAdmin`.`Pedidos_has_UsuarioAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaAdmin`.`Pedidos_has_UsuarioAdmin` (
  `Pedidos_idPedidos` INT NOT NULL,
  `UsuarioAdmin_idUsuarioAdmin` INT NOT NULL,
  `UsuarioAdmin_Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`Pedidos_idPedidos`),
  INDEX `fk_Pedidos_has_UsuarioAdmin_UsuarioAdmin1_idx` (`UsuarioAdmin_idUsuarioAdmin` ASC, `UsuarioAdmin_Rol_idRol` ASC),
  INDEX `fk_Pedidos_has_UsuarioAdmin_Pedidos1_idx` (`Pedidos_idPedidos` ASC),
  CONSTRAINT `fk_Pedidos_has_UsuarioAdmin_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `FerreteriaAdmin`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_UsuarioAdmin_UsuarioAdmin1`
    FOREIGN KEY (`UsuarioAdmin_idUsuarioAdmin` , `UsuarioAdmin_Rol_idRol`)
    REFERENCES `FerreteriaAdmin`.`UsuarioAdmin` (`idUsuarioAdmin` , `Rol_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
